//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorikeet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentsNumber
    {
        public int AppointmentsNumbers { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> LabelID { get; set; }
        public Nullable<int> Number { get; set; }
    }
}
