//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorikeet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int ContactID { get; set; }
        public string ContactAddress { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string ContactType { get; set; }
        public int MemberID { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
