//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorikeet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DebitSystem
    {
        public int DebitID { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public string Details { get; set; }
        public int MemberID { get; set; }
        public Nullable<decimal> RunningTotal { get; set; }
        public int StaffID { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
