//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorikeet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnosi
    {
        public int DiagnosisID { get; set; }
        public int DiagnosisNameID { get; set; }
        public int MemberID { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
