//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorikeet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Label
    {
        public int LabelID { get; set; }
        public Nullable<int> Color { get; set; }
        public string DisplayName { get; set; }
        public string MenuCaption { get; set; }
        public string Shortcut { get; set; }
    }
}
