//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorikeet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int LogID { get; set; }
        public System.DateTime DateTime { get; set; }
        public int ErrorCode { get; set; }
        public string Message { get; set; }
        public int RefreshCode { get; set; }
        public int StaffID { get; set; }
    }
}
