//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorikeet.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LorikeetAppEntities : DbContext
    {
        public LorikeetAppEntities()
            : base("name=LorikeetAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppointmentMember> AppointmentMembers { get; set; }
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<AppointmentsNumber> AppointmentsNumbers { get; set; }
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<AttendanceNumber> AttendanceNumbers { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<DebitSystem> DebitSystems { get; set; }
        public virtual DbSet<Diagnosi> Diagnosis { get; set; }
        public virtual DbSet<DiagnosisName> DiagnosisNames { get; set; }
        public virtual DbSet<GeocodeCache> GeocodeCaches { get; set; }
        public virtual DbSet<Guest> Guests { get; set; }
        public virtual DbSet<Label> Labels { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Lunch> Lunches { get; set; }
        public virtual DbSet<Medication> Medications { get; set; }
        public virtual DbSet<MedicationName> MedicationNames { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<Picture> Pictures { get; set; }
        public virtual DbSet<Resource> Resources { get; set; }
        public virtual DbSet<SignIn> SignIns { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
    }
}
