//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorikeet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lunch
    {
        public int LunchID { get; set; }
        public System.DateTime Date { get; set; }
        public bool Main { get; set; }
        public string Name { get; set; }
        public bool Paid { get; set; }
        public Nullable<int> StaffID { get; set; }
        public bool TakeAway { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
