//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorikeet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int NotesID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> Editable { get; set; }
        public Nullable<int> MemberID { get; set; }
        public string Notes { get; set; }
        public Nullable<int> StaffID { get; set; }
    }
}
