//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorikeet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public int PictureID { get; set; }
        public byte[] MemberFacialRecognition { get; set; }
        public int MemberID { get; set; }
        public byte[] MemberPicture { get; set; }
        public string PictureName { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
