//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lorikeet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignIn
    {
        public int SigninID { get; set; }
        public Nullable<int> GuestID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public string MethodOfSigningIn { get; set; }
        public Nullable<System.DateTime> Timein { get; set; }
        public Nullable<System.DateTime> Timeout { get; set; }
    
        public virtual Guest Guest { get; set; }
        public virtual Member Member { get; set; }
    }
}
