--
-- Script was generated by Devart dbForge Studio for SQL Server, Version 5.5.327.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 3/04/2018 3:57:58 PM
-- Server version: 14.00.1000
--



USE LorikeetApp
GO

IF DB_NAME() <> N'LorikeetApp' SET NOEXEC ON
GO

--
-- Create table [dbo].[Staff]
--
PRINT (N'Create table [dbo].[Staff]')
GO
CREATE TABLE dbo.Staff (
  StaffID int IDENTITY (0, 1),
  LoginID int NOT NULL,
  StaffName nvarchar(50) NOT NULL,
  CONSTRAINT PK_Staff PRIMARY KEY CLUSTERED (StaffID)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[SignIn]
--
PRINT (N'Create table [dbo].[SignIn]')
GO
CREATE TABLE dbo.SignIn (
  SigninID int IDENTITY NOT FOR REPLICATION,
  Timein datetime NULL,
  Timeout datetime NULL,
  MethodOfSigningIn nvarchar(50) NULL,
  MemberID int NULL,
  GuestID int NULL,
  CONSTRAINT PK_SignIn PRIMARY KEY CLUSTERED (SigninID)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[Resources]
--
PRINT (N'Create table [dbo].[Resources]')
GO
CREATE TABLE dbo.Resources (
  UniqueID int IDENTITY,
  ResourceID int NOT NULL,
  ResourceName nvarchar(50) NULL,
  Color int NULL,
  Image image NULL,
  CustomField1 nvarchar(max) NULL,
  CONSTRAINT PK_Resources PRIMARY KEY CLUSTERED (UniqueID)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create table [dbo].[Picture]
--
PRINT (N'Create table [dbo].[Picture]')
GO
CREATE TABLE dbo.Picture (
  PictureID int IDENTITY NOT FOR REPLICATION,
  MemberID int NOT NULL,
  PictureName nvarchar(256) NOT NULL,
  MemberFacialRecognition image NULL,
  MemberPicture image NOT NULL,
  TimeStamp datetime NULL,
  CONSTRAINT PK_Picture PRIMARY KEY CLUSTERED (PictureID)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create table [dbo].[Note]
--
PRINT (N'Create table [dbo].[Note]')
GO
CREATE TABLE dbo.Note (
  NotesID int IDENTITY NOT FOR REPLICATION,
  MemberID int NOT NULL,
  StaffID int NOT NULL,
  Date date NOT NULL,
  Notes nvarchar(max) NOT NULL,
  Editable bit NOT NULL,
  CONSTRAINT PK_Note PRIMARY KEY CLUSTERED (NotesID)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create table [dbo].[Menu]
--
PRINT (N'Create table [dbo].[Menu]')
GO
CREATE TABLE dbo.Menu (
  MenuID int IDENTITY NOT FOR REPLICATION,
  MenuName nvarchar(200) NOT NULL,
  DateMade date NOT NULL,
  CONSTRAINT PK_Menu PRIMARY KEY CLUSTERED (MenuID)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[Member]
--
PRINT (N'Create table [dbo].[Member]')
GO
CREATE TABLE dbo.Member (
  MemberID int NOT NULL,
  Surname nvarchar(100) NOT NULL,
  FirstName nvarchar(100) NOT NULL,
  DateOfBirth date NULL,
  Sex bit NULL,
  CountryOfOrigin nvarchar(200) NULL,
  Aboriginal bit NULL,
  StreetAddress nvarchar(200) NULL,
  PostCode nvarchar(7) NULL,
  Suburb nvarchar(50) NULL,
  State nvarchar(50) NULL,
  Country nvarchar(50) NULL,
  TelephoneNumber nvarchar(20) NULL,
  MobileNumber nvarchar(20) NULL,
  EmailAddress nvarchar(50) NULL,
  DateJoined date NULL,
  ReceiveNewsletter bit NULL,
  ReceiveByMail bit NULL,
  BirthdayCard bit NULL,
  Working bit NULL,
  Volunteering bit NULL,
  Studying bit NULL,
  Archived bit NULL,
  DateAltered date NULL,
  Agency bit NULL,
  CONSTRAINT PK_Member PRIMARY KEY CLUSTERED (MemberID)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[MedicationName]
--
PRINT (N'Create table [dbo].[MedicationName]')
GO
CREATE TABLE dbo.MedicationName (
  MedicationNameID int IDENTITY,
  MedicationName nvarchar(max) NOT NULL,
  CONSTRAINT PK_MedicationName PRIMARY KEY CLUSTERED (MedicationNameID)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create table [dbo].[Lunch]
--
PRINT (N'Create table [dbo].[Lunch]')
GO
CREATE TABLE dbo.Lunch (
  LunchID int IDENTITY NOT FOR REPLICATION,
  Name nvarchar(50) NOT NULL,
  Paid bit NOT NULL,
  TakeAway bit NOT NULL,
  Main bit NOT NULL,
  StaffID int NULL,
  Date date NOT NULL,
  CONSTRAINT PK_Lunch PRIMARY KEY CLUSTERED (LunchID)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[Login]
--
PRINT (N'Create table [dbo].[Login]')
GO
CREATE TABLE dbo.Login (
  LoginID int IDENTITY (0, 1),
  LoginName nvarchar(50) NULL,
  LoginPass nvarchar(50) NULL,
  Access int NULL,
  Pin int NULL,
  CONSTRAINT PK_Login PRIMARY KEY CLUSTERED (LoginID)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[Log]
--
PRINT (N'Create table [dbo].[Log]')
GO
CREATE TABLE dbo.Log (
  LogID int IDENTITY,
  StaffID int NOT NULL,
  ErrorCode int NOT NULL,
  Message nvarchar(max) NOT NULL,
  DateTime datetime NOT NULL,
  RefreshCode int NOT NULL,
  CONSTRAINT PK_Log PRIMARY KEY CLUSTERED (LogID)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create table [dbo].[Labels]
--
PRINT (N'Create table [dbo].[Labels]')
GO
CREATE TABLE dbo.Labels (
  LabelID int IDENTITY,
  Color int NULL,
  DisplayName nvarchar(max) NULL,
  MenuCaption nvarchar(max) NULL,
  CONSTRAINT PK_Labels_1 PRIMARY KEY CLUSTERED (LabelID)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--
-- Create procedure [dbo].[DeleteQuery]
--
GO
PRINT (N'Create procedure [dbo].[DeleteQuery]')
GO
CREATE OR ALTER PROCEDURE dbo.DeleteQuery
(
	@Original_LabelID int,
	@IsNull_Color Int,
	@Original_Color int
)
AS
	SET NOCOUNT OFF;
DELETE FROM [dbo].[Labels] WHERE (([LabelID] = @Original_LabelID) AND ((@IsNull_Color = 1 AND [Color] IS NULL) OR ([Color] = @Original_Color)))
GO

--
-- Create table [dbo].[Guest]
--
PRINT (N'Create table [dbo].[Guest]')
GO
CREATE TABLE dbo.Guest (
  GuestID int IDENTITY (10000, 1) NOT FOR REPLICATION,
  FullName nvarchar(100) NOT NULL,
  Picture image NOT NULL,
  CONSTRAINT PK_Guest PRIMARY KEY CLUSTERED (GuestID)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create table [dbo].[DiagnosisName]
--
PRINT (N'Create table [dbo].[DiagnosisName]')
GO
CREATE TABLE dbo.DiagnosisName (
  DiagnosisNameID int IDENTITY,
  DiagnosisName nvarchar(max) NOT NULL,
  CONSTRAINT PK_DiagnsosisName PRIMARY KEY CLUSTERED (DiagnosisNameID)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create table [dbo].[DebitSystem]
--
PRINT (N'Create table [dbo].[DebitSystem]')
GO
CREATE TABLE dbo.DebitSystem (
  DebitID int IDENTITY NOT FOR REPLICATION,
  MemberID int NOT NULL,
  StaffID int NOT NULL,
  Date date NOT NULL,
  Credit decimal(18, 2) NULL,
  Debit decimal(18, 2) NULL,
  RunningTotal decimal(18, 2) NULL,
  Details nvarchar(200) NULL,
  CONSTRAINT PK_DebitSystem PRIMARY KEY CLUSTERED (DebitID)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[Contact]
--
PRINT (N'Create table [dbo].[Contact]')
GO
CREATE TABLE dbo.Contact (
  ContactID int IDENTITY NOT FOR REPLICATION,
  MemberID int NOT NULL,
  ContactType nvarchar(500) NULL,
  ContactName nvarchar(500) NULL,
  ContactAddress nvarchar(500) NULL,
  ContactPhone nvarchar(20) NULL,
  CONSTRAINT PK_Contact PRIMARY KEY CLUSTERED (ContactID)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[Appointments]
--
PRINT (N'Create table [dbo].[Appointments]')
GO
CREATE TABLE dbo.Appointments (
  UniqueID int IDENTITY,
  Type int NULL,
  StartDate smalldatetime NULL,
  EndDate smalldatetime NULL,
  AllDay bit NULL,
  Subject nvarchar(50) NULL,
  Location nvarchar(50) NULL,
  Description nvarchar(max) NULL,
  Status int NULL,
  Label int NULL,
  ResourceID int NULL,
  ResourceIDs nvarchar(max) NULL,
  ReminderInfo nvarchar(max) NULL,
  RecurrenceInfo nvarchar(max) NULL,
  TimeZoneId nvarchar(max) NULL,
  CustomField1 nvarchar(max) NULL,
  CONSTRAINT PK_Appointments PRIMARY KEY CLUSTERED (UniqueID)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create user [Lorikeet]
--
PRINT (N'Create user [Lorikeet]')
GO
CREATE USER Lorikeet
  FOR LOGIN lorikeet
  WITH DEFAULT_SCHEMA = db_datareader
GO

--
-- Create user [hobbsb]
--
PRINT (N'Create user [hobbsb]')
GO
CREATE USER hobbsb
  WITHOUT LOGIN
GO

--
-- Create table [dbo].[Medication]
--
PRINT (N'Create table [dbo].[Medication]')
GO
CREATE TABLE dbo.Medication (
  MedicationID int IDENTITY NOT FOR REPLICATION,
  MemberID int NOT NULL,
  MedicationNameID int NOT NULL,
  CONSTRAINT PK_Medication PRIMARY KEY CLUSTERED (MedicationID)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[Diagnosis]
--
PRINT (N'Create table [dbo].[Diagnosis]')
GO
CREATE TABLE dbo.Diagnosis (
  DiagnosisID int IDENTITY NOT FOR REPLICATION,
  MemberID int NOT NULL,
  DiagnosisNameID int NOT NULL,
  CONSTRAINT PK_Diagnosis PRIMARY KEY CLUSTERED (DiagnosisID)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[AttendanceNumbers]
--
PRINT (N'Create table [dbo].[AttendanceNumbers]')
GO
CREATE TABLE dbo.AttendanceNumbers (
  AttendanceNumbersID int IDENTITY,
  Date date NULL,
  Number int NULL,
  CONSTRAINT PK_AttendanceNumbers_AttendanceNumbersID PRIMARY KEY CLUSTERED (AttendanceNumbersID)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[Attendance]
--
PRINT (N'Create table [dbo].[Attendance]')
GO
CREATE TABLE dbo.Attendance (
  AttendanceID int IDENTITY,
  Date date NOT NULL,
  MemberID int NULL,
  CONSTRAINT PK_Attendance PRIMARY KEY CLUSTERED (AttendanceID)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[AppointmentMember]
--
PRINT (N'Create table [dbo].[AppointmentMember]')
GO
CREATE TABLE dbo.AppointmentMember (
  MemberActivityID int IDENTITY,
  AppointmentsID int NOT NULL,
  MemberID int NOT NULL,
  CONSTRAINT PK_AppointmentMember PRIMARY KEY CLUSTERED (MemberActivityID)
)
ON [PRIMARY]
GO

--
-- Create procedure [dbo].[GetYearCounts]
--
GO
PRINT (N'Create procedure [dbo].[GetYearCounts]')
GO
CREATE OR ALTER PROCEDURE dbo.GetYearCounts
    @year INT
AS
    SELECT YEAR(dbo.Attendance.Date) AS y,
           MONTH(dbo.Attendance.Date) AS m,
           COUNT(*) AS tally
    FROM   MESSAGE
    WHERE  YEAR(dbo.Attendance.Date) = @year
           AND SUBJECT <> 'Welcome' --exclude default messages
    GROUP BY
           YEAR(dbo.Attendance.Date),
           MONTH(dbo.Attendance.Date);
GO
-- 
-- Dumping data for table AppointmentMember
--
-- Table LorikeetApp.dbo.AppointmentMember does not contain any data (it is empty)
-- 
-- Dumping data for table Appointments
--
-- Table LorikeetApp.dbo.Appointments does not contain any data (it is empty)
-- 
-- Dumping data for table Attendance
--
-- Table LorikeetApp.dbo.Attendance does not contain any data (it is empty)
-- 
-- Dumping data for table AttendanceNumbers
--
-- Table LorikeetApp.dbo.AttendanceNumbers does not contain any data (it is empty)
-- 
-- Dumping data for table Contact
--
-- Table LorikeetApp.dbo.Contact does not contain any data (it is empty)
-- 
-- Dumping data for table DebitSystem
--
-- Table LorikeetApp.dbo.DebitSystem does not contain any data (it is empty)
-- 
-- Dumping data for table Diagnosis
--
-- Table LorikeetApp.dbo.Diagnosis does not contain any data (it is empty)
-- 
-- Dumping data for table DiagnosisName
--
-- Table LorikeetApp.dbo.DiagnosisName does not contain any data (it is empty)
-- 
-- Dumping data for table Guest
--
-- Table LorikeetApp.dbo.Guest does not contain any data (it is empty)
-- 
-- Dumping data for table Labels
--
-- Table LorikeetApp.dbo.Labels does not contain any data (it is empty)
-- 
-- Dumping data for table Log
--
-- Table LorikeetApp.dbo.Log does not contain any data (it is empty)
-- 
-- Dumping data for table Login
--
SET IDENTITY_INSERT dbo.Login ON
GO
INSERT dbo.Login(LoginID, LoginName, LoginPass, Access, Pin) VALUES (0, NULL, NULL, NULL, NULL)
INSERT dbo.Login(LoginID, LoginName, LoginPass, Access, Pin) VALUES (1, N'Byron', N'Byron', 10, 1111)
INSERT dbo.Login(LoginID, LoginName, LoginPass, Access, Pin) VALUES (2, N'Test', N'Person', 8, 2222)
GO
SET IDENTITY_INSERT dbo.Login OFF
GO
-- 
-- Dumping data for table Lunch
--
-- Table LorikeetApp.dbo.Lunch does not contain any data (it is empty)
-- 
-- Dumping data for table Medication
--
-- Table LorikeetApp.dbo.Medication does not contain any data (it is empty)
-- 
-- Dumping data for table MedicationName
--
-- Table LorikeetApp.dbo.MedicationName does not contain any data (it is empty)
-- 
-- Dumping data for table Member
--
-- Table LorikeetApp.dbo.Member does not contain any data (it is empty)
-- 
-- Dumping data for table Menu
--
-- Table LorikeetApp.dbo.Menu does not contain any data (it is empty)
-- 
-- Dumping data for table Note
--
-- Table LorikeetApp.dbo.Note does not contain any data (it is empty)
-- 
-- Dumping data for table Picture
--
-- Table LorikeetApp.dbo.Picture does not contain any data (it is empty)
-- 
-- Dumping data for table Resources
--
-- Table LorikeetApp.dbo.Resources does not contain any data (it is empty)
-- 
-- Dumping data for table SignIn
--
-- Table LorikeetApp.dbo.SignIn does not contain any data (it is empty)
-- 
-- Dumping data for table Staff
--
SET IDENTITY_INSERT dbo.Staff ON
GO
INSERT dbo.Staff(StaffID, LoginID, StaffName) VALUES (0, 0, N'NA')
INSERT dbo.Staff(StaffID, LoginID, StaffName) VALUES (1, 1, N'Byron')
INSERT dbo.Staff(StaffID, LoginID, StaffName) VALUES (3, 2, N'Test Person')
GO
SET IDENTITY_INSERT dbo.Staff OFF
GO

USE LorikeetApp
GO

IF DB_NAME() <> N'LorikeetApp' SET NOEXEC ON
GO

--
-- Create foreign key [FK_Staff_Login] on table [dbo].[Staff]
--
PRINT (N'Create foreign key [FK_Staff_Login] on table [dbo].[Staff]')
GO
ALTER TABLE dbo.Staff
  ADD CONSTRAINT FK_Staff_Login FOREIGN KEY (LoginID) REFERENCES dbo.Login (LoginID)
GO

--
-- Create foreign key [FK_Lunch_Staff] on table [dbo].[Lunch]
--
PRINT (N'Create foreign key [FK_Lunch_Staff] on table [dbo].[Lunch]')
GO
ALTER TABLE dbo.Lunch
  ADD CONSTRAINT FK_Lunch_Staff FOREIGN KEY (StaffID) REFERENCES dbo.Staff (StaffID)
GO

--
-- Create foreign key [FK_DebitSystem_Member] on table [dbo].[DebitSystem]
--
PRINT (N'Create foreign key [FK_DebitSystem_Member] on table [dbo].[DebitSystem]')
GO
ALTER TABLE dbo.DebitSystem WITH NOCHECK
  ADD CONSTRAINT FK_DebitSystem_Member FOREIGN KEY (MemberID) REFERENCES dbo.Member (MemberID) NOT FOR REPLICATION
GO

--
-- Create foreign key [FK_DebitSystem_Staff] on table [dbo].[DebitSystem]
--
PRINT (N'Create foreign key [FK_DebitSystem_Staff] on table [dbo].[DebitSystem]')
GO
ALTER TABLE dbo.DebitSystem
  ADD CONSTRAINT FK_DebitSystem_Staff FOREIGN KEY (StaffID) REFERENCES dbo.Staff (StaffID)
GO

--
-- Disable foreign key [FK_DebitSystem_Member] on table [dbo].[DebitSystem]
--
PRINT (N'Disable foreign key [FK_DebitSystem_Member] on table [dbo].[DebitSystem]')
GO
ALTER TABLE dbo.DebitSystem
  NOCHECK CONSTRAINT FK_DebitSystem_Member
GO

--
-- Create foreign key [FK_SignIn_Guest] on table [dbo].[SignIn]
--
PRINT (N'Create foreign key [FK_SignIn_Guest] on table [dbo].[SignIn]')
GO
ALTER TABLE dbo.SignIn
  ADD CONSTRAINT FK_SignIn_Guest FOREIGN KEY (GuestID) REFERENCES dbo.Guest (GuestID)
GO

--
-- Create foreign key [FK_SignIn_Member] on table [dbo].[SignIn]
--
PRINT (N'Create foreign key [FK_SignIn_Member] on table [dbo].[SignIn]')
GO
ALTER TABLE dbo.SignIn WITH NOCHECK
  ADD CONSTRAINT FK_SignIn_Member FOREIGN KEY (MemberID) REFERENCES dbo.Member (MemberID) NOT FOR REPLICATION
GO

--
-- Disable foreign key [FK_SignIn_Member] on table [dbo].[SignIn]
--
PRINT (N'Disable foreign key [FK_SignIn_Member] on table [dbo].[SignIn]')
GO
ALTER TABLE dbo.SignIn
  NOCHECK CONSTRAINT FK_SignIn_Member
GO

--
-- Create foreign key [FK_Picture_Member] on table [dbo].[Picture]
--
PRINT (N'Create foreign key [FK_Picture_Member] on table [dbo].[Picture]')
GO
ALTER TABLE dbo.Picture WITH NOCHECK
  ADD CONSTRAINT FK_Picture_Member FOREIGN KEY (MemberID) REFERENCES dbo.Member (MemberID) NOT FOR REPLICATION
GO

--
-- Disable foreign key [FK_Picture_Member] on table [dbo].[Picture]
--
PRINT (N'Disable foreign key [FK_Picture_Member] on table [dbo].[Picture]')
GO
ALTER TABLE dbo.Picture
  NOCHECK CONSTRAINT FK_Picture_Member
GO

--
-- Create foreign key [FK_Contact_Member] on table [dbo].[Contact]
--
PRINT (N'Create foreign key [FK_Contact_Member] on table [dbo].[Contact]')
GO
ALTER TABLE dbo.Contact WITH NOCHECK
  ADD CONSTRAINT FK_Contact_Member FOREIGN KEY (MemberID) REFERENCES dbo.Member (MemberID) NOT FOR REPLICATION
GO

--
-- Create foreign key [FK_Medication_Member] on table [dbo].[Medication]
--
PRINT (N'Create foreign key [FK_Medication_Member] on table [dbo].[Medication]')
GO
ALTER TABLE dbo.Medication WITH NOCHECK
  ADD CONSTRAINT FK_Medication_Member FOREIGN KEY (MemberID) REFERENCES dbo.Member (MemberID) NOT FOR REPLICATION
GO

--
-- Disable foreign key [FK_Medication_Member] on table [dbo].[Medication]
--
PRINT (N'Disable foreign key [FK_Medication_Member] on table [dbo].[Medication]')
GO
ALTER TABLE dbo.Medication
  NOCHECK CONSTRAINT FK_Medication_Member
GO

--
-- Create foreign key [FK_Diagnosis_Member] on table [dbo].[Diagnosis]
--
PRINT (N'Create foreign key [FK_Diagnosis_Member] on table [dbo].[Diagnosis]')
GO
ALTER TABLE dbo.Diagnosis WITH NOCHECK
  ADD CONSTRAINT FK_Diagnosis_Member FOREIGN KEY (MemberID) REFERENCES dbo.Member (MemberID) NOT FOR REPLICATION
GO

--
-- Disable foreign key [FK_Diagnosis_Member] on table [dbo].[Diagnosis]
--
PRINT (N'Disable foreign key [FK_Diagnosis_Member] on table [dbo].[Diagnosis]')
GO
ALTER TABLE dbo.Diagnosis
  NOCHECK CONSTRAINT FK_Diagnosis_Member
GO

--
-- Create foreign key [FK_AppointmentMember_AppointmentMember] on table [dbo].[AppointmentMember]
--
PRINT (N'Create foreign key [FK_AppointmentMember_AppointmentMember] on table [dbo].[AppointmentMember]')
GO
ALTER TABLE dbo.AppointmentMember
  ADD CONSTRAINT FK_AppointmentMember_AppointmentMember FOREIGN KEY (MemberActivityID) REFERENCES dbo.AppointmentMember (MemberActivityID)
GO
SET NOEXEC OFF
GO